<Gerenciador>:#:kivy
    BoxLayout:
        orientation:'vertical'
        Label:
            text:'Conversor de Moedas'
        BoxLayout:
            orientation:'horizontal'
            BoxLayout:
                orientation:'vertical'
                Label:
                    text:'De:'
            BoxLayout:
                orientation:'vertical'
                Label:
                    text:'Para:'